### ISSUE TITLE
Error while starting

### ISSUE THREAD

**Issue by vidukapoor** [lapanti/ts-react-boilerplate#110]
https://github.com/lapanti/ts-react-boilerplate#requirements
its giving some of the errors,

Its just a new start.

`yarn develop`
Module build failed: TypeError: Cannot read property 'indexOf' of undefined
    at transform (/path/ts-react-boilerplate/node_modules/react-hot-loader/dist/webpack.development.js:74:14)
    at Object.transform$1 (/Users/path/ts-react-boilerplate/node_modules/react-hot-loader/dist/webpack.development.js:116:14)

`yarn build`
CLIENT <path/ts-react-boilerplate/node_modules/webpack/lib/Chunk.js:460
CLIENT          throw new Error(
CLIENT         ^
CLIENT Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by instanceof Entrypoint instead
CLIENT     at Chunk.get (/Users/path/ts-react-boilerplate/node_modules/webpack/lib/Chunk.js:460:9)

**Comment by lapanti** [comment]
Hi, thanks for trying it out, unfortunately I haven't had the time to work on this project in a long while (and don't unfortunately have any time on my hands at the moment either) so a lot of these things might be stale

**Comment by vidukapoor** [comment]
Here I am sharing some changes in package.json, by removing some of the `^`, any how you can have a look as per your availability.

`"devDependencies": {
    "@types/express": "^4.11.0",
    "@types/history": "^4.6.2",
    "@types/jest": "^22.0.1",
    "@types/nock": "^9.1.1",
    "@types/react": "^16.0.34",
    "@types/react-dom": "^16.0.3",
    "@types/react-hot-loader": "^3.0.5",
    "@types/react-redux": "^5.0.14",
    "@types/react-router-dom": "^4.2.3",
    "awesome-typescript-loader": "^4.0.0",
    "babel": "^6.23.0",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-env": "^1.6.1",
    "concurrently": "^3.5.1",
    "copy-webpack-plugin": "4.3.1",
    "coveralls": "^3.0.0",
    "css-loader": "^0.28.8",
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "enzyme-to-json": "^3.3.0",
    "extract-text-webpack-plugin": "3.0.2",
    "gitbook-cli": "^2.3.2",
    "gitbook-plugin-advanced-emoji": "^0.2.2",
    "gitbook-plugin-anker-enable": "^0.0.4",
    "gitbook-plugin-edit-link": "^2.0.2",
    "gitbook-plugin-github": "^3.0.0",
    "gitbook-plugin-prism": "^2.3.0",
    "gitbook-plugin-theme-default": "^1.0.7",
    "husky": "^0.14.3",
    "jest": "^22.0.5",
    "lint-staged": "^7.0.0",
    "nock": "^9.1.6",
    "node-sass": "^4.7.2",
    "prettier": "^1.10.2",
    "react-hot-loader": "^4.0.0",
    "react-test-renderer": "^16.2.0",
    "sass-lint": "^1.12.1",
    "sass-loader": "^6.0.6",
    "source-map-loader": "^0.2.3",
    "style-loader": "^0.20.0",
    "ts-jest": "^22.0.1",
    "tslint": "^5.8.0",
    "tslint-config-prettier": "^1.6.0",
    "tslint-react": "^3.3.3",
    "typescript": "^2.6.2",
    "webpack": "4.0.0",
    "webpack-cli": "3.2.3",
    "webpack-dev-server": "3.0.0"
  }`

**Comment by lapanti** [comment]
next time please format it a bit. But anyway as it seems most packages have been updated (or their types have been updated), the only way to fix this would be to update the dependencies and then fix the migration problems. but as I stated unfortunately I'm not going to have time to do that in a while
